INSERT INTO estado(nombre) VALUES('Nueva');
INSERT INTO estado(nombre) VALUES('En revisión');
INSERT INTO estado(nombre) VALUES('Aceptada');
INSERT INTO estado(nombre) VALUES('Rechazada');
INSERT INTO estado(nombre) VALUES('Cancelada');

INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Partido Aprista Peruano', 'APRA', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/APRA.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Fuerza Popular', 'FP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Fuerza_Popular.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Acción Popular', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/AP_Accion-Polular.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Alianza para el progreso', 'A', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/APP_Alianza-para-el-progreso.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Perú Posible', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/peru_posible.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Avanza País', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Avanza-Pais.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Democracia Directa', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Democracia-directa.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Frente Amplio', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Frente-Amplio.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Frepap', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Frepap.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Juntos por el Perú', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Juntos_por_el_Peru.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Partido Morado', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Partido_Morado.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Partido Solidaridad Nacional', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Partido_solidad_nacional.jpg' );
INSERT INTO partido_politico(nombre, nombre_corto, descripcion, estado, fecha_registro, fecha_actualizacion,foto)VALUES ('Somos Perú', 'PP', '', 1, GETDATE(), GETDATE(), 'Partidos_Politicos/Somos_Peru.jpg' );

INSERT INTO cargo_politico(nombre, estado, fecha_registro, fecha_actualizacion) VALUES ('Presidente',  1, GETDATE(), GETDATE());
INSERT INTO cargo_politico(nombre, estado, fecha_registro, fecha_actualizacion) VALUES ('Congresista', 1, getdate(), GETDATE());

INSERT INTO candidato (nombre, apellido, partido_politico_id, cargo_politico_id,fecha_registro, fecha_actualizacion, estado, id_usuario, foto) VALUES ('Alejandro', 'Toledo Manrique',5,1,getdate(),getdate(), 1, 1, 'Candidatos/Alejandro_Toledo.jpg');
INSERT INTO candidato (nombre, apellido, partido_politico_id, cargo_politico_id,fecha_registro, fecha_actualizacion, estado, id_usuario, foto) VALUES ('Keiko', 'Fujimori',2,1,getdate(),getdate(), 1, 1, 'Candidatos/Keiko_Fujimori.jpg');
INSERT INTO candidato (nombre, apellido, partido_politico_id, cargo_politico_id,fecha_registro, fecha_actualizacion, estado, id_usuario, foto) VALUES ('Rosa', 'Bartra',2,2,getdate(),getdate(), 1, 1, 'Candidatos/Rosa Bartra.jpg');
INSERT INTO candidato (nombre, apellido, partido_politico_id, cargo_politico_id,fecha_registro, fecha_actualizacion, estado, id_usuario, foto) VALUES ('Mauricio', 'Mulder',1,1,getdate(),getdate(), 1, 1, 'Candidatos/Mauricio_Mulder.jpg');
INSERT INTO candidato (nombre, apellido, partido_politico_id, cargo_politico_id,fecha_registro, fecha_actualizacion, estado, id_usuario, foto) VALUES ('Cesar', 'Acuña',4,1,getdate(),getdate(), 1, 1, 'Candidatos/Cesar_Acuña.jpg');

INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Toledo-Alquiler de oficina', 'A horas 03:00 p.m. en la notaría Paino, se le hizo entrega al señor Alejandro Toledo dentro de un sobre cerrado la suma de 50,000 dólares por concepto de firma de contrato de alquier y primeros dos meses, de una ofina ubicada en Avenida Manuel Olguín 211, Surco; sin embargo, dicho inmueble se encuentra en proceso de venta hacia otra persona, loq ue constituye un delito posible de lavado de activos. Presento mi denuncia en calidad de testigo y adjunto fotos prueba.',1, 1,1,'05/04/2019',1);
INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Tráfico de influencias - Peculado', 'La señora Rosa Bartra fue de visita al domicilio de Armando Lino Llerena Victoria con DNI 06051772, ubicado en el Jirón Napo 145, en el distrito de Breña para concretar la coordinación de postulaciòn del referido señor al puesto JEFE DE ODPE en la ONPE. Se obtubo como resultado final que dicho señor fue elegido para el puesto el 20/03/2019 como se puede constatar en la url http://www.onpe.gob.pe/modTransparencia/Convocatorias/CP/JEFE-ODPE-EMC2019-ResultFinal-12mar.pdf' ,3, 1,2,'05/04/2019',1 );
INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Tráfico de influencias - Peculado', 'En el domicilio del señor Mauricio Mulder ubicado en Alfonso Ugarte No. 1012, Breña; se llevó a cabo una reunión para contratar en el INPE al hijo de su amigo, joven llamado Cristhian Nestor Ramos Neira con DNI 72634424. Y que sea el único postulante al puesto de Tecnólogo Médico Radiólogo en Ica, como consta en el enlace https://www.inpe.gob.pe/concurso-a/documentos/2893-pi-cas-036-tecnologo-radiologo/file.html posteriormente ganando la postulación con un puntaje de 14 el cual es muy bajo, se observa en el enlace el resultado https://www.inpe.gob.pe/concurso-a/documentos/2937-eco-cas-036-tecnologo/file.html. Resulta sospechosa porque el joven es recién egresado y no cumple con el perfil solicitado.',4, 1,1,'05/04/2019',1);
INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Incubrimiento real', 'Esta denuncia constitucional deberá seguir un largo camino en el Congreso de la República. Pero no es la primera acusación que se presenta sobre el mismo caso. El 2 de abril último, los miembros de Fuerza Popular y el Apra en la Subcomisión de Acusaciones Constitucionales enviaron al archivo la denuncia constitucional contra Pedro Chávarry, presentada por el Frente Amplio, por el caso de la violación de las oficinas lacradas del Ministerio Público. Fueron cuatro votos contra tres.',2, 1,2,'05/04/2019',1);
INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Incubrimiento real', 'Esta denuncia constitucional deberá seguir un largo camino en el Congreso de la República. Pero no es la primera acusación que se presenta sobre el mismo caso. El 2 de abril último, los miembros de Fuerza Popular y el Apra en la Subcomisión de Acusaciones Constitucionales enviaron al archivo la denuncia constitucional contra Pedro Chávarry, presentada por el Frente Amplio, por el caso de la violación de las oficinas lacradas del Ministerio Público. Fueron cuatro votos contra tres.',2, 1,3,'05/04/2019', 1);
INSERT INTO denuncia (titulo, descripcion,candidato_id, id_usuario, estado_id, fecha_registro, total_seguimiento)VALUES('Incubrimiento real', 'Esta denuncia constitucional deberá seguir un largo camino en el Congreso de la República. Pero no es la primera acusación que se presenta sobre el mismo caso. El 2 de abril último, los miembros de Fuerza Popular y el Apra en la Subcomisión de Acusaciones Constitucionales enviaron al archivo la denuncia constitucional contra Pedro Chávarry, presentada por el Frente Amplio, por el caso de la violación de las oficinas lacradas del Ministerio Público. Fueron cuatro votos contra tres.',2, 1,2,'05/04/2019', 1);


INSERT INTO seguimiento_denuncia (usuario_id,denuncia_id,fecha_registro,fecha_actualizacion,estado) VALUES(1,1,GETDATE(), GETDATE(), 1);
INSERT INTO seguimiento_denuncia (usuario_id,denuncia_id,fecha_registro,fecha_actualizacion,estado) VALUES(1,2,GETDATE(), GETDATE(), 1);
INSERT INTO seguimiento_denuncia (usuario_id,denuncia_id,fecha_registro,fecha_actualizacion,estado) VALUES(1,3,GETDATE(), GETDATE(), 1);
INSERT INTO seguimiento_denuncia (usuario_id,denuncia_id,fecha_registro,fecha_actualizacion,estado) VALUES(1,4,GETDATE(), GETDATE(), 1);
